name: riverpod_ddd_template # Your application name
description: "A new Flutter project." # Your application description
publish_to: 'none'
version: 1.0.0+1 # Your application version

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  flutter_dotenv: ^5.2.1
  flutter_image_compress: ^2.4.0
  flutter_svg: ^2.2.0
  image_picker: ^1.1.2 # Should add configuration to android and ios
  path: ^1.9.1
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  prompt_generator: ^1.0.1
  res_generator: ^0.1.5

flutter:
  uses-material-design: true