name: riverpod_ddd_template # Your application name
description: "A new Flutter project." # Your application description
publish_to: 'none'
version: 1.0.0+1 # Your application version

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  animated_flip_counter: ^0.3.4
  auto_route: ^10.1.0+1
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  #  device_frame_plus: ^1.5.0 # If you need to test different screens
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  flutter_dotenv: ^5.2.1
  flutter_easyloading: ^3.0.5
  flutter_image_compress: ^2.4.0
  flutter_svg: ^2.2.0
  image_picker: ^1.1.2 # Should add configuration to android and ios
  path: ^1.9.1
  path_provider: ^2.1.4
  pull_to_refresh: ^2.0.0
  safe_device: ^1.2.1
  shimmer: ^3.0.0
  url_launcher: ^6.3.1 # Should add configuration to android and ios
  widget_and_text_animator: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.2.3
  build_runner: ^2.5.3
  custom_lint: ^0.7.5
  flutter_lints: ^6.0.0
  freezed: ^3.0.6
  json_serializable: ^6.9.4
  prompt_generator: ^1.0.1
  res_generator: ^0.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/tr/